### ISSUE TITLE
Auto complete issue

### ISSUE THREAD

**Issue by padmkris123** [hannaholl/angular-input-dropdown#10]
If I add the attribute autocomplete="off" to <input-dropdown> it doesnt work. Is there any other way to switch autocomplete off?

**Comment by nirajkrz** [comment]
@padmkris123, 

> The autocomplete attribute specifies whether or not an **input field** should have autocomplete enabled.

that means you may have to pass this attribute value to the Input field in directive and then use. 
For Ex-
`<input-dropdown input-autocomplete="off"`

and then inside directive---  
`scope: {
      defaultDropdownItems: '=',
      inputAutocomplete ='@'
       inputName: '@',
      inputPlaceholder: '@' .`

`<input type="text"' +
           'name="{{inputName}}"' +
           'placeholder="{{inputPlaceholder}}"' +
           'ng-model="inputValue"' +
autocomplete ="{{inputAutocomplete }}"`

Let me know if it helps.

**Comment by hannaholl** [comment]
Thanks for the reply @nirajkrz, that should be the solution I think.

@padmkris123 Let me know if you're still having issues and I'll post another example.

Thanks!

**Comment by padmkris123** [comment]
@nirajkrz This works well. Thank you.
