### ISSUE TITLE
I couldnt customerize my ng-model

### ISSUE THREAD

**Issue by LuckyLin** [hannaholl/angular-input-dropdown#14]
Hello,

I want to empty the block after I select/input value and push a button. But there is not ng-model which I can specify by myself. I dont understand 'ng-model="inputValue"'. Could you help me? Thanks.

Best

**Comment by archcorsair** [comment]
I believe the selection is stored in `selected-item` and not in `ng-model`.

**Comment by LuckyLin** [comment]
Thank you @archcorsair, I empty the block by changing the viewValue of it. :)

**Comment by paigudepooja** [comment]
Hi,

I am not able to get the value of selected-item in controller.
