### ISSUE TITLE
Default value for input

### ISSUE THREAD

**Issue by jrm2k6** [hannaholl/angular-input-dropdown#21]
I am trying to set a default value to be used by the input on the initial render, but it looks like it doesn't accept it.

```
<input-dropdown
                        selected-item="timepickerData.selectedStartTime"
                        default-dropdown-items="timepickerData.intervals"
                        item-selected-method="onStartTimeSelected(item)"
                        allow-custom-input="true"
                >
                </input-dropdown>
```

In my controller I have:

```
timepickerData.selectedStartTime = '5:00 am';
```

which is also one of the suggestions available in default-dropdown-items.

Any idea what I should do to be able to render that default value?

**Comment by kodelio** [comment]
Hi,

How did you solve the problem ?
