### ISSUE TITLE
$apply already in progress error

### ISSUE THREAD

**Issue by karahisarli** [hannaholl/angular-input-dropdown#3]
when you use "enter" key on item selection, you always get $apply already in progress error with chrome, angular version 1.3.0, this is not happening with 1.4.0

**Comment by hannaholl** [comment]
Hi,

This has only been built and tested for Angular 1.3.10+ unfortunately. However I'm not getting this issue in 1.3.0 either. If you could please give me some more details, which version of chrome you're on etc, I could still have a look at it?

Thanks
