### ISSUE TITLE
allow-custom-input="true" does not work.

### ISSUE THREAD

**Issue by pavanesh2009** [hannaholl/angular-input-dropdown#7]
Hello Hanna, 

I am trying to integrate it and use it in combination input box with autocomplete dropdown.
While using allow-custom-input="true" fields is still shown as invalid and only becomes valid if user selects from the available listed options.

Here is the plunker pointing to the problem:
https://plnkr.co/edit/UXNVukk0MwmSBmr4BlK8?p=preview

Thanks in advance!

**Comment by Geetakokate** [comment]
Hi @pavanesh2009 , allow-custom-input="true" not worked for me also, I did some code in my controller,

>  this.filterDropdown = function(userInput) {
>   return $http.get('/cities/search/' + userInput)
>     .then(function(request) {
>       var dropdownArray = request.data;
>       dropdownArray = dropdownArray.filter(function(val) { return val !== null; });
>       if(!dropdownArray.length)
>         this.city = userInput;
>       angular.forEach(dropdownArray, function(city){
>         if(city!=userInput){
>           this.city = userInput;
>         }
>       });
>       return dropdownArray;
>     });
>   };

Is worked for me.

**Comment by hannaholl** [comment]
Hi @pavanesh2009!

Sorry I didn't manage to get back to you sooner. I hope you weren't blocked on this too long.

I had a look at your Plunker and noticed it's using an older version of the inputDropdown.js.
I understand you probably forked it off mine, I realised I didn't update the demo with the new version, I'm sorry about that!

I've updated the demo and it's all working. Please try updating the inputDropdown.js to the latest version in your example and see if that works. Here is my update demo https://embed.plnkr.co/4HZ0CS/preview.

Let me know if you're still having issues!

Thanks for your input @Geetakokate! That looks like a good way to access the input value. I wasn't sure if that functionality should be included in the directive or not, let me know if you have any suggestions.

Cheers!

**Comment by Geetakokate** [comment]
okk @hannaholl  got it :)

**Comment by hannaholl** [comment]
Great! :)
